version: "3.9"

services:
  vite:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules # agar node_modules host tidak mengganggu container
    command: npm run dev
